# Generated by Django 3.2.13 on 2022-04-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20220414_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.DateField(default="2022-04-14"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='month',
            field=models.PositiveIntegerField(default=3, verbose_name='reporting month'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='year',
            field=models.PositiveIntegerField(default=2022, verbose_name='reporting year'),
        ),
    ]
