# Generated by Django 3.2.13 on 2022-04-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20220414_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='claimed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='finished_at',
            field=models.DateTimeField(),
        ),
    ]
