# Generated by Django 3.2.13 on 2022-04-15 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0008_alter_ticket_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='claimed_at',
            new_name='picked_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='claimed_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='picked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
