# Generated by Django 3.2.13 on 2022-04-15 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0010_auto_20220415_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='took_up_at',
            new_name='undertook_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='took_up_by',
        ),
        migrations.AddField(
            model_name='ticket',
            name='undertook_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='undertake_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
