# Generated by Django 3.2.13 on 2022-04-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20220415_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='additional information'),
        ),
    ]
