# Generated by Django 3.2.13 on 2022-04-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_ticket_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='written_at',
            field=models.DateTimeField(),
        ),
    ]
