# Generated by Django 3.2.13 on 2022-05-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_alter_comment_written_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Example', max_length=128, verbose_name='reporting year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='month',
            field=models.PositiveIntegerField(default=4, verbose_name='reporting month'),
        ),
    ]
